services:
  mongo:
    container_name: mongo-cont
    image: mongo
    hostname: localhost
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: lib_mgmt
    volumes:
      - ./db_files:/root/db_files
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
